### ISSUE TITLE
error:Error:Unable to resolve module ../../models/detr_resnet50.ptl from F:\PyTorchDemo\MyFirstProject\src\examples\ObjectDetectionExample.tsx

### ISSUE THREAD

**Issue by RyanShun-511** [facebookresearch/playtorch#18]
### Tutorial Select

Get Started Manually

### Feedback

I installed the relevant software according to tutorial instructions, and after executing the relevant steps, the Node window showed this problem. I am very confused, and I hope to get your answer.

Problem description:

None of these files exist:
  * detr_resnet50.ptl
  * models\detr_resnet50.ptl\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  25 | const modelInfo: ModelInfo = {
  26 |   name: 'DETR',
> 27 |   model: require('../../models/detr_resnet50.ptl'),
     |                   ^
  28 | };
  29 |
  30 | const objectColors = [
    at ModuleResolver.resolveDependency (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\node-haste\DependencyGraph.js:413:43)
    at Object.resolve (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\lib\transformHelpers.js:317:42)
    at resolve (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:629:33)
    at F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:644:33)
    at F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:137:24)

**Comment by raedle** [comment]
@RyanShun-511 , thanks for reporting this issue. We were able to reproduce it on our end and will submit a fix soon!

In the meantime, you can try if the follow steps unblock you:

1. `cd F:\PyTorchDemo\MyFirstProject\models`
2. Change line 27 in `make_models.py` from `spec = Path(f"{name}.{MODEL_EXTENSION}.live.spec.json").read_text()`  to `spec = Path(f"{name}.{MODEL_EXTENSION}.live.spec.json").read_text(encoding="UTF-8")`
3. `python3 -m venv venv`
4. `.\venv\Scripts\activate`
5. `pip install -r requirements.txt`
6. `python make_models.py`

The steps above export the `ptl` models. Re-run the `npx react-native run-android` to build and deploy the app in the emulator or a physical device.

**Comment by RyanShun-511** [comment]
@raedle Thank you for your reply. Following your steps, I can see the model generated in the export_image_Classification_models function under F:\PyTorchDemo\MyFirstProject\ Models. The detr_resnet50.ptl file does not exist. Later parts of the program, such as MNIST models, may not be generated.
Excuse me, how can I solve this problem?

Description on node:
error: Error: Unable to resolve module ../../models/detr_resnet50.ptl from F:\PyTorchDemo\MyFirstProject\src\examples\ObjectDetectionExample.tsx:

None of these files exist:
  * detr_resnet50.ptl
  * models\detr_resnet50.ptl\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  25 | const modelInfo: ModelInfo = {
  26 |   name: 'DETR',
> 27 |   model: require('../../models/detr_resnet50.ptl'),
     |                   ^
  28 | };
  29 |
  30 | const objectColors = [
    at ModuleResolver.resolveDependency (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\node-haste\DependencyGraph.js:413:43)
    at Object.resolve (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\lib\transformHelpers.js:317:42)
    at resolve (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:629:33)
    at F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:644:33)
    at F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (F:\PyTorchDemo\MyFirstProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:137:24)

**Comment by RyanShun-511** [comment]
@raedle Or you have the detr_resnet50.ptl model file and the model files generated in the export_mnist_model and export_NLP_models functions for me to download. I put it directly in the F:\PyTorchDemo\MyFirstProject\ Models folder.
Thank you for your careful answer.

**Comment by RyanShun-511** [comment]
During the execution of the make_model.py file, I downloaded the model from the URL myself. You can put the program on your phone. Thank you for your answers.

**Comment by raedle** [comment]
@RyanShun-511 to help narrow down the issue, please provide a list of model files (i.e., `*.ptl` files) that are generated when following the [steps provided in my comment above](https://github.com/pytorch/live/issues/18#issuecomment-999275166)

Thank you!

**Comment by azhugreat** [comment]
@raedle  I have faced this problem myself, and I have generated these files. 
The following are the generated files:
![image](https://user-images.githubusercontent.com/50580109/153702331-940cb3fc-7aa7-42af-9208-38e610755ddb.png)

The file size are 353MB, so I wonder whether I should upload them to you there.

**Comment by raedle** [comment]
The models are no longer part of the template, and with the new PlayTorch API and the PlayTorch app + Snack there are now better alternatives to experiment with on-device ML models.

Closing this issue due to inactivity. Please reopen if this is still ongoing!
