### ISSUE TITLE
app crashes on android

### ISSUE THREAD

**Issue by yMayanand** [facebookresearch/playtorch#40]
### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

I am trying to run Image Classification model on Android. I had followed manual instructions for setup on linux machine. Everything is fine till the last step of installation and app gets succesfully installed on my android phone running android v9(Pie). But app crashes as soon as it is launched at start.

**Comment by chrisklaiber** [comment]
Hi @yMayanand,

Would you please attach a crash log from the Metro logs and from `adb logcat`? I expect this would contain a stack trace and help to pinpoint the root issue.

Thanks!

**Comment by raedle** [comment]
@yMayanand, PyTorch Live supports Android 10+ (see [README](https://github.com/pytorch/live/blob/main/README.md))

>PyTorch Live apps may target Android 10.0 (API 21) and iOS 12.0 or newer.

It seems that the shared libraries for PyTorch Android (`libpytorch_jni_lite`) are missing. Can you check if the `*.so` are in the `app-debug.apk`?

* Go to `cd <PROJECT>/android/app/build/outputs/apk/debug`
* `unzip app-debug.apk`
* Check if the lib folder for your device's architecture has the `*.so` files
  * e.g., `cd <PROJECT>/android/app/build/outputs/apk/debug/lib/x86`

The project is currently building for `arm64-v8a`, `armeabi-v7a`, `x86`, and `x86_64`.

**Comment by yMayanand** [comment]
@raedle My phones architecture is ```arm64-v8a``` and i had checked the folder 
```<PROJECT>/android/app/build/outputs/apk/debug/lib/arm64-v8a``` for ```*.so``` files. It has all the  ```*.so``` files and i  also looked for ```libpytorch_jni_lite``` file it had that too.

**Comment by raedle** [comment]
@yMayanand, does the app also crash on a device Android 10.0+ (API 21+)? If yes, would you be able to share the project in a repo?

**Comment by akashraj9828** [comment]
@raedle  I am running on Android 11 and it crashes for me as well...

![image](https://user-images.githubusercontent.com/29796785/160596588-20588ac6-1347-4f62-928c-235516853a93.png)


Here's the logcat of crash
 
```
03-29 16:14:56.279 18407 18407 W unknown:ReactNative: Packager connection already open, nooping.
03-29 16:14:56.315  1532  1709 I ActivityTaskManager: Displayed org.pytorch.live.example/.MainActivity: +739ms
03-29 16:14:56.320  1532  1692 D EventSequenceValidator: dec AccIntentStartedEvents to 1
03-29 16:14:56.508 18407 18460 D SoLoader: About to load: libhermes.so
03-29 16:14:56.508 18407 18460 D SoLoader: libhermes.so not found on /data/user/0/org.pytorch.live.example/lib-main
03-29 16:14:56.508 18407 18460 D SoLoader: libhermes.so found on /data/app/~~oQy-oOr9y0FDzYve7IgTEw==/org.pytorch.live.example-voXhERWr7pFbLgSsuzABsw==/lib/arm64
03-29 16:14:56.508 18407 18460 D SoLoader: Not resolving dependencies for libhermes.so
03-29 16:14:56.517 18407 18460 D SoLoader: Loaded: libhermes.so
03-29 16:14:56.517 18407 18460 D SoLoader: About to load: libhermes-executor-debug.so
03-29 16:14:56.518 18407 18460 D SoLoader: libhermes-executor-debug.so not found on /data/user/0/org.pytorch.live.example/lib-main
03-29 16:14:56.518 18407 18460 D SoLoader: libhermes-executor-debug.so found on /data/app/~~oQy-oOr9y0FDzYve7IgTEw==/org.pytorch.live.example-voXhERWr7pFbLgSsuzABsw==/lib/arm64
03-29 16:14:56.518 18407 18460 D SoLoader: Not resolving dependencies for libhermes-executor-debug.so
03-29 16:14:56.547 18407 18460 D SoLoader: Loaded: libhermes-executor-debug.so
03-29 16:14:56.568 18407 18460 E AndroidRuntime: FATAL EXCEPTION: create_react_context
03-29 16:14:56.568 18407 18460 E AndroidRuntime: Process: org.pytorch.live.example, PID: 18407
03-29 16:14:56.568 18407 18460 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8facebook3jni12jtype_traitsIiE11kDescriptorE" referenced by "/data/app/~~oQy-oOr9y0FDzYve7IgTEw==/org.pytorch.live.example-voXhERWr7pFbLgSsuzABsw==/lib/arm64/libpytorch_jni_lite.so"...
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at org.pytorch.rn.core.jsi.PyTorchCoreJSIModule.<clinit>(PyTorchCoreJSIModule.java:25)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at org.pytorch.rn.core.PyTorchCorePackage.createNativeModules(PyTorchCorePackage.java:30)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
03-29 16:14:56.568 18407 18460 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
03-29 16:14:56.571  1532 18461 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
03-29 16:14:56.571  1532  8668 W ActivityTaskManager:   Force finishing activity org.pytorch.live.example/.MainActivity
03-29 16:14:56.574  1532 18461 W DropBoxManagerService: Dropping: data_app_crash (1526 > 0 bytes)
03-29 16:14:56.578 18407 18460 I Process : Sending signal. PID: 18407 SIG: 9
03-29 16:14:56.580  1532  1710 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
03-29 16:14:56.581  1532  1710 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
03-29 16:14:56.630  1532  3795 I ActivityManager: Process org.pytorch.live.example (pid 18407) has died: prcp TOP
```


Just to be sure i confirmed if i have `libpytorch_jni_lite.so` file bundled 
and it is present in the installed app

![image](https://user-images.githubusercontent.com/29796785/160596278-6d82c23a-6968-44c3-b035-dbd7716a0288.png)

**Comment by yMayanand** [comment]
I have tried first option but the problem was not solved, i am eagerly waiting for next version
so that problem would get solved implicitly.

**Comment by raedle** [comment]
The PlayTorch 0.2.0 series introduced new JavaScript interfaces to PyTorch APIs for flexible data processing and inference that replace MobileModel.execute and Live Spec JSON. See the core package's [README](https://github.com/pytorch/live/blob/0.2-stable/react-native-pytorch-core/README.md#example-usage) for example usage.

Closing this issue due to inactivity. Please reopen if this is still ongoing!
