### ISSUE TITLE
Cannot run tutorial project in Get Started Manually on Windows

### ISSUE THREAD

**Issue by t4rf9** [facebookresearch/playtorch#53]
### Version

0.13.0

### Problem Area

Website/Documentation

### Steps to Reproduce

First, try to run the project on an Android device:
1. `npx react-native init MyFirstProject --template react-native-template-pytorch-live`
2. `cd MyFirstProject`
3. `npx react-native run-android`
Then I find the app installed successfully on the device, but fails while bundling.
The output goes like: (the following error message is obtained after manually running `python make_models.py`)
```
error: Error: Unable to resolve module ../../models/detr_resnet50.ptl from C:\Users\t4rf9\PyTorchLiveProject\src\examples\ObjectDetectionExample.tsx:

None of these files exist:
  * detr_resnet50.ptl
  * models\detr_resnet50.ptl\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  25 | const modelInfo: ModelInfo = {
  26 |   name: 'DETR',
> 27 |   model: require('../../models/detr_resnet50.ptl'),
     |                   ^
  28 | };
  29 |
  30 | const objectColors = [
    at ModuleResolver.resolveDependency (C:\Users\t4rf9\PyTorchLiveProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (C:\Users\t4rf9\PyTorchLiveProject\node_modules\metro\src\node-haste\DependencyGraph.js:413:43)
    at Object.resolve (C:\Users\t4rf9\PyTorchLiveProject\node_modules\metro\src\lib\transformHelpers.js:317:42)
    at resolve (C:\Users\t4rf9\PyTorchLiveProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:629:33)
    at C:\Users\t4rf9\PyTorchLiveProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\t4rf9\PyTorchLiveProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:644:33)
    at C:\Users\t4rf9\PyTorchLiveProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\t4rf9\PyTorchLiveProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:137:24)
```
Then, in an attempt to fix this, I run `python make_models.py` within `models/`，but fails within `export_image_segmentation_models()`. Other 3 `export_xxx_models()` functions returns normally.

By the way, the torch, torchvision, torchaudio and scipy version listed in requirements.txt is unaccessible via pip, and is only availble via conda. If the versions of the packages don't match those in requirements.txt, the error in [https://github.com/pytorch/live/issues/51](url) will happen. However, the required versions of packages still give an error.

The error message goes:
```
(PyTorchLive) PS C:\Users\t4rf9\PyTorchLiveProject\models> python .\make_models.py
torch version 1.10.0
Exporting image segmentation models
Traceback (most recent call last):
  File "C:\Users\t4rf9\PyTorchLiveProject\models\make_models.py", line 124, in <module>
    main()
  File "C:\Users\t4rf9\PyTorchLiveProject\models\make_models.py", line 118, in main
    export_image_segmentation_models()
  File "C:\Users\t4rf9\PyTorchLiveProject\models\make_models.py", line 57, in export_image_segmentation_models
    model = torch.hub.load(
  File "C:\tools\miniconda3\envs\PyTorchLive\lib\site-packages\torch\hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\tools\miniconda3\envs\PyTorchLive\lib\site-packages\torch\hub.py", line 428, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\t4rf9/.cache\torch\hub\facebookresearch_detr_main\hubconf.py", line 32, in detr_resnet50
    model = _make_detr("resnet50", dilation=False, num_classes=num_classes)
  File "C:\Users\t4rf9/.cache\torch\hub\facebookresearch_detr_main\hubconf.py", line 15, in _make_detr
    backbone = Backbone(backbone_name, train_backbone=True, return_interm_layers=mask, dilation=dilation)
  File "C:\Users\t4rf9/.cache\torch\hub\facebookresearch_detr_main\models\backbone.py", line 89, in __init__
    backbone = getattr(torchvision.models, name)(
  File "C:\tools\miniconda3\envs\PyTorchLive\lib\site-packages\torchvision\models\resnet.py", line 300, in resnet50
    return _resnet('resnet50', Bottleneck, [3, 4, 6, 3], pretrained, progress,
  File "C:\tools\miniconda3\envs\PyTorchLive\lib\site-packages\torchvision\models\resnet.py", line 262, in _resnet
    state_dict = load_state_dict_from_url(model_urls[arch],
  File "C:\tools\miniconda3\envs\PyTorchLive\lib\site-packages\torch\hub.py", line 590, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "C:\tools\miniconda3\envs\PyTorchLive\lib\site-packages\torch\serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\tools\miniconda3\envs\PyTorchLive\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```
A glance at google results tells me that this might be caused by the difference of PyTorch versions between the pretrained model saver and the loader, but I am not sure about this.

I advice the project owner to:
1. fix the "failed finding central directory" bug;
2. add `python make_models.py` into the instructions, or make it automatically run;
3. update the python packages used to the latest versions.

### Expected Results

Following the instructions in the tutorial, the example project can be successfully run.

**Comment by t4rf9** [comment]
I solved this problem by executing `export_image_segmentation_models()` with wsl-ubuntu python3.8.12,
torch==1.10.2, torchvision==0.11.3, torchaudio==0.10.2, transformers==4.6.1, scipy==1.8.0.
However, my windows python3.10.4 still fails.

**Comment by JonathanSum** [comment]
But we will have another problems. For example the tutorials uses other models, such as bert_qa.ptl. We can't find it in the internet and do not know how to connect it.
